version: "3.9"

services:
  gateway:
    image: ghcr.io/sunyuboalisa/alisa-gateway:latest
    container_name: alisa-gateway
    ports:
      - 8100:8080
    env_file:
      - ./alisa-gateway.env
    restart: always
    networks:
      - my_network

networks:
  my_network:
